version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis-stack:
    image: bitnami/redis:latest
    container_name: redis-stack
    networks:
      - default
    ports:
      - "6379:6379"
    volumes:
      - ./redis-stack/data:/bitnami/redis/data
      - ./redis-stack/conf:/bitnami/redis/conf
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redispassword
      - REDIS_AOF_ENABLED=yes
    command: redis-server --appendonly yes --dir /bitnami/redis/data --requirepass "password"

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge
    name: default_network
